export const indianStates = [
    "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
  ];


export const mockTypes = ["Historical", "Adventure", "Nature", "Religious", "Cultural"];


export const mockPlaces = [
  {
    id: 1,
    zone: "North",
    state: "Uttarakhand",
    city: "Rishikesh",
    name: "Laxman Jhula",
    type: "Spiritual",
    establishmentYear: "Early 20th Century",
    timeNeeded: "2",
    image_url: "https://hblimg.mmtcdn.com/content/hubble/img/agra/mmt/activities/m_activities-agra-taj-mahal_l_400_640.jpg",
    googleReviewRating: 4.6,
    entranceFee: 0,
    airportWithin50km: "Jolly Grant Airport, Dehradun",
    weeklyOff: "None",
    significance: "Hindu Mythology, Adventure Spot",
    dslrAllowed: "Yes",
    googleReviewCount: 1.2,
    bestTimeToVisit: "October - March",
    bestMonthToVisit: "December",
  },
  {
    id: 2,
    zone: "West",
    state: "Rajasthan",
    city: "Jaipur",
    name: "Hawa Mahal",
    type: "Historical",
    establishmentYear: "1799",
    timeNeeded: "1.5",
    image_url: "https://hblimg.mmtcdn.com/content/hubble/img/delhi/mmt/activities/m_activities_delhi_red_fort_l_341_817.jpg",
    googleReviewRating: 4.5,
    entranceFee: 50,
    airportWithin50km: "Jaipur International Airport",
    weeklyOff: "None",
    significance: "Architectural Marvel, Royal History",
    dslrAllowed: "Yes",
    googleReviewCount: 2.5,
    bestTimeToVisit: "November - February",
    bestMonthToVisit: "January",
  },
  {
    id: 3,
    zone: "South",
    state: "Tamil Nadu",
    city: "Chennai",
    name: "Marina Beach",
    type: "Beach",
    establishmentYear: "Natural",
    timeNeeded: "3",
    image_url: "https://hblimg.mmtcdn.com/content/hubble/img/amritsar/mmt/activities/m_activities_amritsar_golden_temple_l_427_639.jpg",
    googleReviewRating: 4.4,
    entranceFee: 0,
    airportWithin50km: "Chennai International Airport",
    weeklyOff: "None",
    significance: "Longest Urban Beach in India",
    dslrAllowed: "Yes",
    googleReviewCount: 3.0,
    bestTimeToVisit: "December - February",
    bestMonthToVisit: "January",
  },
  {
    id: 4,
    zone: "East",
    state: "West Bengal",
    city: "Darjeeling",
    name: "Tiger Hill",
    type: "Nature",
    establishmentYear: "Natural",
    timeNeeded: "2",
    image_url: "https://hblimg.mmtcdn.com/content/hubble/img/jaipur/mmt/activities/m_activities_amber_fort_2_l_436_573.jpg",
    googleReviewRating: 4.7,
    entranceFee: 20,
    airportWithin50km: "Bagdogra Airport",
    weeklyOff: "None",
    significance: "Sunrise Viewpoint for Kanchenjunga",
    dslrAllowed: "Yes",
    googleReviewCount: 1.8,
    bestTimeToVisit: "October - April",
    bestMonthToVisit: "March",
  },
  {
    id: 5,
    zone: "Central",
    state: "Madhya Pradesh",
    city: "Khajuraho",
    name: "Khajuraho Temples",
    type: "Cultural",
    establishmentYear: "10th Century",
    timeNeeded: "4",
    image_url: "https://hblimg.mmtcdn.com/content/hubble/img/jaipur/mmt/activities/m_activities-jaipur-hawa-mahal_l_400_640.jpg",
    googleReviewRating: 4.8,
    entranceFee: 40,
    airportWithin50km: "Khajuraho Airport",
    weeklyOff: "None",
    significance: "UNESCO World Heritage Site",
    dslrAllowed: "Yes",
    googleReviewCount: 2.2,
    bestTimeToVisit: "October - February",
    bestMonthToVisit: "December",
  },
];

